site_name: Easier WebAssembly with twr-wasm
site_url: https://twiddlingbits.dev/docsite/
repo_url: https://github.com/twiddlingbits/twr-wasm
edit_uri: 'tree/main/docs'
site_description: Documentation and examples to execute C/C++ code in a browser, using WebAssembly and clang directly.
site_dir: azure/docsite/
theme: 
  name: material  
  features:
   - navigation.tabs
   - navigation.tabs.sticky
   - content.code.copy
plugins:
  - search
  - meta-descriptions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Getting Started:
    - Installation: gettingstarted/installation.md
    - Hello World: gettingstarted/helloworld.md
    - Basic Steps: gettingstarted/basicsteps.md
    - Passing Arguments: gettingstarted/parameters.md
    - Consoles: gettingstarted/stdio.md
    - Character Encoding: gettingstarted/charencoding.md
    - Debugging: gettingstarted/debugging.md
    - Compiler, Linker, Memory: gettingstarted/compiler-opts.md
  - Examples: 
    - Overview: examples/examples-overview.md
    - hello world: examples/examples-helloworld.md
    - divcon: examples/examples-divcon.md
    - terminal: examples/examples-terminal.md
    - multi-io: examples/examples-multi-io.md
    - fft: examples/examples-fft.md
    - balls: examples/examples-balls.md
    - pong: examples/examples-pong.md
    - maze: examples/examples-maze.md
    - callC: examples/examples-callc.md
    - library: examples/examples-lib.md
    - libc++: examples/examples-libcxx.md
  - C/C++ API:
    - General: api/api-c-general.md
    - Localization: api/api-c-localization.md
    - Draw 2D: api/api-c-d2d.md
    - Console Char I/O: api/api-c-con.md
    - Standard C Library: api/api-c-stdlib.md
    - libc++: api/api-libcpp.md
    - Audio: api/api-c-audio.md
  - TypeScript API:
    - Modules: api/api-ts-modules.md
    - Consoles: api/api-ts-consoles.md
    - Memory: api/api-ts-memory.md
    - Libraries: api/api-ts-library.md
  - More:
    - Wasm Runtime Limitations: more/wasm-problem.md
    - Import Resolution: more/imports.md
    - SharedArrayBuffers Note: more/production.md
    - Building the Source: more/building.md

  


